name: "Bug Report"
description: "Report a bug"
title: "[BUG] "
labels:

* bug

body:

* type: textarea
  id: summary
  attributes:
  label: Summary
  description: Describe the issue
  validations:
  required: true
